# Generated by Django 4.1.3 on 2023-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geultarae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hint', models.CharField(help_text='힌트', max_length=200)),
                ('date_available', models.DateTimeField()),
            ],
        ),
    ]
