# Generated by Django 4.1.3 on 2023-01-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geultarae', '0002_writing'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
