# Generated by Django 4.1.3 on 2023-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geultarae', '0003_writing_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Chosen writings',
            field=models.JSONField(default=[], verbose_name='List of ids chosen by user'),
            preserve_default=False,
        ),
    ]
