# Generated by Django 4.1.3 on 2023-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geultarae', '0005_remove_user_chosen writings_user_writings'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='plot',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='writings',
            field=models.CharField(blank=True, max_length=200, verbose_name='String of ids'),
        ),
    ]
